version: "3.8"

services:
  db:
    container_name: osint-framework-db
    image: postgres:alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-osint_framework}
      POSTGRES_USER: ${POSTGRES_USER:-osint_framework}
      PGDATA: /data/postgres
    healthcheck:
      test: pg_isready -U osint_framework
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres
    ports:
      - "5432:5432"
  server:
    container_name: osint-framework-server
    image: osint-framework-server:1.0
    depends_on:
      - db
    environment:
      POSTGRES_DATABASE: osint
      POSTGRES_PASSWORD: osint_framework
      POSTGRES_USER: osint_framework
      POSTGRES_HOST: osint-framework-db
      POSTGRES_PORT: 5432
    healthcheck:
      test: curl --fail --silent http://localhost:8888/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    build:
      context: .
      target: osint-framework-server
      dockerfile: docker/server/Dockerfile
    ports:
      - "8888:8888"
    networks:
      - postgres
networks:
  postgres:
    driver: bridge
volumes:
  postgres:
